# Generated by Django 4.2.4 on 2023-08-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('email2', models.EmailField(max_length=255, unique=True, verbose_name='Original Email')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Username')),
                ('username2', models.CharField(max_length=150, unique=True, verbose_name='Original Username')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('is_premium', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
